name: Publish docker images

on:
  push:
    tags:
      - v0.0.**

jobs:
  push_to_registry:
    name: Push Docker image to the registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker images
        run: make -C deployments/docker deploy services
      - name: Publish docker images
        id: push
        run: |
          docker images
          docker tag veraison/vts:latest ghcr.io/thomas-fossati/veraison/vts:${{  github.ref_name }}
          digest="`docker push ghcr.io/thomas-fossati/veraison/vts:${{  github.ref_name }} | grep 'digest:' 
 cut -d' ' -f3`"
          echo "digest=${digest}" >> $GITHUB_OUTPUT
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
      
